# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gregmeeresyoung\workspace\NagapifaceMocap\nagapi\designer\MocapEditDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(365, 562)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Identiication = QtGui.QWidget()
        self.Identiication.setObjectName(_fromUtf8("Identiication"))
        self.gridLayout = QtGui.QGridLayout(self.Identiication)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.Identiication)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_SmartClas = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_SmartClas.setCheckable(False)
        self.groupBox_SmartClas.setChecked(False)
        self.groupBox_SmartClas.setObjectName(_fromUtf8("groupBox_SmartClas"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_SmartClas)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.groupBox_SmartClas)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.spinBox_smartBoxSize = QtGui.QSpinBox(self.groupBox_SmartClas)
        self.spinBox_smartBoxSize.setMaximum(100)
        self.spinBox_smartBoxSize.setProperty("value", 40)
        self.spinBox_smartBoxSize.setObjectName(_fromUtf8("spinBox_smartBoxSize"))
        self.horizontalLayout_11.addWidget(self.spinBox_smartBoxSize)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_SmartClas)
        self.groupBox_CustemR = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_CustemR.setCheckable(False)
        self.groupBox_CustemR.setObjectName(_fromUtf8("groupBox_CustemR"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_CustemR)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_CustemR)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_colID = QtGui.QSpinBox(self.groupBox_CustemR)
        self.spinBox_colID.setMinimum(1)
        self.spinBox_colID.setMaximum(3)
        self.spinBox_colID.setObjectName(_fromUtf8("spinBox_colID"))
        self.horizontalLayout_5.addWidget(self.spinBox_colID)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_CustemR)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_CustemR)
        self.horizontalSlider.setMaximum(400)
        self.horizontalSlider.setProperty("value", 15)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.spinBox_width = QtGui.QSpinBox(self.groupBox_CustemR)
        self.spinBox_width.setMaximum(400)
        self.spinBox_width.setProperty("value", 15)
        self.spinBox_width.setObjectName(_fromUtf8("spinBox_width"))
        self.horizontalLayout_3.addWidget(self.spinBox_width)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_CustemR)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.horizontalSlider_2 = QtGui.QSlider(self.groupBox_CustemR)
        self.horizontalSlider_2.setMaximum(640)
        self.horizontalSlider_2.setProperty("value", 15)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.spinBox_height = QtGui.QSpinBox(self.groupBox_CustemR)
        self.spinBox_height.setMaximum(640)
        self.spinBox_height.setProperty("value", 15)
        self.spinBox_height.setObjectName(_fromUtf8("spinBox_height"))
        self.horizontalLayout_4.addWidget(self.spinBox_height)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_CustemR)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.Identiication)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinBox_tag = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox_tag.setObjectName(_fromUtf8("spinBox_tag"))
        self.horizontalLayout_6.addWidget(self.spinBox_tag)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget.addTab(self.Identiication, _fromUtf8(""))
        self.OutputChannels = QtGui.QWidget()
        self.OutputChannels.setObjectName(_fromUtf8("OutputChannels"))
        self.gridLayout_2 = QtGui.QGridLayout(self.OutputChannels)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_x = QtGui.QGroupBox(self.OutputChannels)
        self.groupBox_x.setFlat(False)
        self.groupBox_x.setCheckable(True)
        self.groupBox_x.setObjectName(_fromUtf8("groupBox_x"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_x)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_x_2 = QtGui.QGroupBox(self.groupBox_x)
        self.groupBox_x_2.setFlat(True)
        self.groupBox_x_2.setObjectName(_fromUtf8("groupBox_x_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_x_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_x = QtGui.QHBoxLayout()
        self.horizontalLayout_x.setObjectName(_fromUtf8("horizontalLayout_x"))
        self.radioButton_noF_x = QtGui.QRadioButton(self.groupBox_x_2)
        self.radioButton_noF_x.setChecked(True)
        self.radioButton_noF_x.setObjectName(_fromUtf8("radioButton_noF_x"))
        self.horizontalLayout_x.addWidget(self.radioButton_noF_x)
        self.radioButton_lowPassF_x = QtGui.QRadioButton(self.groupBox_x_2)
        self.radioButton_lowPassF_x.setObjectName(_fromUtf8("radioButton_lowPassF_x"))
        self.horizontalLayout_x.addWidget(self.radioButton_lowPassF_x)
        self.radioButton_gAve_x = QtGui.QRadioButton(self.groupBox_x_2)
        self.radioButton_gAve_x.setObjectName(_fromUtf8("radioButton_gAve_x"))
        self.horizontalLayout_x.addWidget(self.radioButton_gAve_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_x)
        self.horizontalLayout_x_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_x_2.setObjectName(_fromUtf8("horizontalLayout_x_2"))
        self.label_x = QtGui.QLabel(self.groupBox_x_2)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.horizontalLayout_x_2.addWidget(self.label_x)
        self.doubleSpinBox_feq_x = QtGui.QDoubleSpinBox(self.groupBox_x_2)
        self.doubleSpinBox_feq_x.setDecimals(3)
        self.doubleSpinBox_feq_x.setMaximum(1.0)
        self.doubleSpinBox_feq_x.setSingleStep(0.001)
        self.doubleSpinBox_feq_x.setProperty("value", 0.03)
        self.doubleSpinBox_feq_x.setObjectName(_fromUtf8("doubleSpinBox_feq_x"))
        self.horizontalLayout_x_2.addWidget(self.doubleSpinBox_feq_x)
        self.label_x_2 = QtGui.QLabel(self.groupBox_x_2)
        self.label_x_2.setObjectName(_fromUtf8("label_x_2"))
        self.horizontalLayout_x_2.addWidget(self.label_x_2)
        self.spinBox_filterBuffSize_x = QtGui.QSpinBox(self.groupBox_x_2)
        self.spinBox_filterBuffSize_x.setMaximum(500)
        self.spinBox_filterBuffSize_x.setProperty("value", 150)
        self.spinBox_filterBuffSize_x.setObjectName(_fromUtf8("spinBox_filterBuffSize_x"))
        self.horizontalLayout_x_2.addWidget(self.spinBox_filterBuffSize_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_x_2)
        self.horizontalLayout_13.addWidget(self.groupBox_x_2)
        self.gridLayout_2.addWidget(self.groupBox_x, 0, 0, 1, 1)
        self.groupBox_y = QtGui.QGroupBox(self.OutputChannels)
        self.groupBox_y.setFlat(False)
        self.groupBox_y.setCheckable(True)
        self.groupBox_y.setObjectName(_fromUtf8("groupBox_y"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_y)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.groupBox_y_2 = QtGui.QGroupBox(self.groupBox_y)
        self.groupBox_y_2.setFlat(True)
        self.groupBox_y_2.setObjectName(_fromUtf8("groupBox_y_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_y_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_y_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_y_2.setObjectName(_fromUtf8("horizontalLayout_y_2"))
        self.radioButton_noF_y = QtGui.QRadioButton(self.groupBox_y_2)
        self.radioButton_noF_y.setChecked(True)
        self.radioButton_noF_y.setObjectName(_fromUtf8("radioButton_noF_y"))
        self.horizontalLayout_y_2.addWidget(self.radioButton_noF_y)
        self.radioButton_lowPassF_y = QtGui.QRadioButton(self.groupBox_y_2)
        self.radioButton_lowPassF_y.setObjectName(_fromUtf8("radioButton_lowPassF_y"))
        self.horizontalLayout_y_2.addWidget(self.radioButton_lowPassF_y)
        self.radioButton_gAve_y = QtGui.QRadioButton(self.groupBox_y_2)
        self.radioButton_gAve_y.setObjectName(_fromUtf8("radioButton_gAve_y"))
        self.horizontalLayout_y_2.addWidget(self.radioButton_gAve_y)
        self.verticalLayout_6.addLayout(self.horizontalLayout_y_2)
        self.horizontalLayout_y = QtGui.QHBoxLayout()
        self.horizontalLayout_y.setObjectName(_fromUtf8("horizontalLayout_y"))
        self.label_y = QtGui.QLabel(self.groupBox_y_2)
        self.label_y.setObjectName(_fromUtf8("label_y"))
        self.horizontalLayout_y.addWidget(self.label_y)
        self.doubleSpinBox_feq_y = QtGui.QDoubleSpinBox(self.groupBox_y_2)
        self.doubleSpinBox_feq_y.setDecimals(3)
        self.doubleSpinBox_feq_y.setMaximum(1.0)
        self.doubleSpinBox_feq_y.setSingleStep(0.001)
        self.doubleSpinBox_feq_y.setProperty("value", 0.03)
        self.doubleSpinBox_feq_y.setObjectName(_fromUtf8("doubleSpinBox_feq_y"))
        self.horizontalLayout_y.addWidget(self.doubleSpinBox_feq_y)
        self.label_y_2 = QtGui.QLabel(self.groupBox_y_2)
        self.label_y_2.setObjectName(_fromUtf8("label_y_2"))
        self.horizontalLayout_y.addWidget(self.label_y_2)
        self.spinBox_filterBuffSize_y = QtGui.QSpinBox(self.groupBox_y_2)
        self.spinBox_filterBuffSize_y.setMaximum(500)
        self.spinBox_filterBuffSize_y.setProperty("value", 150)
        self.spinBox_filterBuffSize_y.setObjectName(_fromUtf8("spinBox_filterBuffSize_y"))
        self.horizontalLayout_y.addWidget(self.spinBox_filterBuffSize_y)
        self.verticalLayout_6.addLayout(self.horizontalLayout_y)
        self.horizontalLayout_14.addWidget(self.groupBox_y_2)
        self.gridLayout_2.addWidget(self.groupBox_y, 1, 0, 1, 1)
        self.groupBox_w = QtGui.QGroupBox(self.OutputChannels)
        self.groupBox_w.setFlat(False)
        self.groupBox_w.setCheckable(True)
        self.groupBox_w.setChecked(False)
        self.groupBox_w.setObjectName(_fromUtf8("groupBox_w"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_w)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.groupBox_w_2 = QtGui.QGroupBox(self.groupBox_w)
        self.groupBox_w_2.setFlat(True)
        self.groupBox_w_2.setObjectName(_fromUtf8("groupBox_w_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_w_2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_w = QtGui.QHBoxLayout()
        self.horizontalLayout_w.setObjectName(_fromUtf8("horizontalLayout_w"))
        self.radioButton_noF_w = QtGui.QRadioButton(self.groupBox_w_2)
        self.radioButton_noF_w.setChecked(True)
        self.radioButton_noF_w.setObjectName(_fromUtf8("radioButton_noF_w"))
        self.horizontalLayout_w.addWidget(self.radioButton_noF_w)
        self.radioButton_lowPassF_w = QtGui.QRadioButton(self.groupBox_w_2)
        self.radioButton_lowPassF_w.setObjectName(_fromUtf8("radioButton_lowPassF_w"))
        self.horizontalLayout_w.addWidget(self.radioButton_lowPassF_w)
        self.radioButton_gAve_w = QtGui.QRadioButton(self.groupBox_w_2)
        self.radioButton_gAve_w.setObjectName(_fromUtf8("radioButton_gAve_w"))
        self.horizontalLayout_w.addWidget(self.radioButton_gAve_w)
        self.verticalLayout_7.addLayout(self.horizontalLayout_w)
        self.horizontalLayout_w_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_w_2.setObjectName(_fromUtf8("horizontalLayout_w_2"))
        self.label_w = QtGui.QLabel(self.groupBox_w_2)
        self.label_w.setObjectName(_fromUtf8("label_w"))
        self.horizontalLayout_w_2.addWidget(self.label_w)
        self.doubleSpinBox_feq_w = QtGui.QDoubleSpinBox(self.groupBox_w_2)
        self.doubleSpinBox_feq_w.setDecimals(3)
        self.doubleSpinBox_feq_w.setMaximum(1.0)
        self.doubleSpinBox_feq_w.setSingleStep(0.001)
        self.doubleSpinBox_feq_w.setProperty("value", 0.03)
        self.doubleSpinBox_feq_w.setObjectName(_fromUtf8("doubleSpinBox_feq_w"))
        self.horizontalLayout_w_2.addWidget(self.doubleSpinBox_feq_w)
        self.label_w_2 = QtGui.QLabel(self.groupBox_w_2)
        self.label_w_2.setObjectName(_fromUtf8("label_w_2"))
        self.horizontalLayout_w_2.addWidget(self.label_w_2)
        self.spinBox_filterBuffSize_w = QtGui.QSpinBox(self.groupBox_w_2)
        self.spinBox_filterBuffSize_w.setMaximum(500)
        self.spinBox_filterBuffSize_w.setProperty("value", 150)
        self.spinBox_filterBuffSize_w.setObjectName(_fromUtf8("spinBox_filterBuffSize_w"))
        self.horizontalLayout_w_2.addWidget(self.spinBox_filterBuffSize_w)
        self.verticalLayout_7.addLayout(self.horizontalLayout_w_2)
        self.horizontalLayout_17.addWidget(self.groupBox_w_2)
        self.gridLayout_2.addWidget(self.groupBox_w, 2, 0, 1, 1)
        self.groupBox_h = QtGui.QGroupBox(self.OutputChannels)
        self.groupBox_h.setFlat(False)
        self.groupBox_h.setCheckable(True)
        self.groupBox_h.setChecked(False)
        self.groupBox_h.setObjectName(_fromUtf8("groupBox_h"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox_h)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.groupBox_h_2 = QtGui.QGroupBox(self.groupBox_h)
        self.groupBox_h_2.setFlat(True)
        self.groupBox_h_2.setObjectName(_fromUtf8("groupBox_h_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_h_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_h_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_h_2.setObjectName(_fromUtf8("horizontalLayout_h_2"))
        self.radioButton_noF_h = QtGui.QRadioButton(self.groupBox_h_2)
        self.radioButton_noF_h.setChecked(True)
        self.radioButton_noF_h.setObjectName(_fromUtf8("radioButton_noF_h"))
        self.horizontalLayout_h_2.addWidget(self.radioButton_noF_h)
        self.radioButton_lowPassF_h = QtGui.QRadioButton(self.groupBox_h_2)
        self.radioButton_lowPassF_h.setObjectName(_fromUtf8("radioButton_lowPassF_h"))
        self.horizontalLayout_h_2.addWidget(self.radioButton_lowPassF_h)
        self.radioButton_gAve_h = QtGui.QRadioButton(self.groupBox_h_2)
        self.radioButton_gAve_h.setObjectName(_fromUtf8("radioButton_gAve_h"))
        self.horizontalLayout_h_2.addWidget(self.radioButton_gAve_h)
        self.verticalLayout_8.addLayout(self.horizontalLayout_h_2)
        self.horizontalLayout_h = QtGui.QHBoxLayout()
        self.horizontalLayout_h.setObjectName(_fromUtf8("horizontalLayout_h"))
        self.label_h = QtGui.QLabel(self.groupBox_h_2)
        self.label_h.setObjectName(_fromUtf8("label_h"))
        self.horizontalLayout_h.addWidget(self.label_h)
        self.doubleSpinBox_feq_h = QtGui.QDoubleSpinBox(self.groupBox_h_2)
        self.doubleSpinBox_feq_h.setDecimals(3)
        self.doubleSpinBox_feq_h.setMaximum(1.0)
        self.doubleSpinBox_feq_h.setSingleStep(0.001)
        self.doubleSpinBox_feq_h.setProperty("value", 0.03)
        self.doubleSpinBox_feq_h.setObjectName(_fromUtf8("doubleSpinBox_feq_h"))
        self.horizontalLayout_h.addWidget(self.doubleSpinBox_feq_h)
        self.label_h_2 = QtGui.QLabel(self.groupBox_h_2)
        self.label_h_2.setObjectName(_fromUtf8("label_h_2"))
        self.horizontalLayout_h.addWidget(self.label_h_2)
        self.spinBox_filterBuffSize_h = QtGui.QSpinBox(self.groupBox_h_2)
        self.spinBox_filterBuffSize_h.setMaximum(500)
        self.spinBox_filterBuffSize_h.setProperty("value", 150)
        self.spinBox_filterBuffSize_h.setObjectName(_fromUtf8("spinBox_filterBuffSize_h"))
        self.horizontalLayout_h.addWidget(self.spinBox_filterBuffSize_h)
        self.verticalLayout_8.addLayout(self.horizontalLayout_h)
        self.horizontalLayout_20.addWidget(self.groupBox_h_2)
        self.gridLayout_2.addWidget(self.groupBox_h, 3, 0, 1, 1)
        self.tabWidget.addTab(self.OutputChannels, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.label.setBuddy(self.horizontalSlider)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.horizontalSlider_2, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox_height.setValue)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox_width.setValue)
        QtCore.QObject.connect(self.spinBox_width, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider.setValue)
        QtCore.QObject.connect(self.spinBox_height, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_2.setValue)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Clasification", None))
        self.groupBox_SmartClas.setTitle(_translate("Dialog", "Auto regen", None))
        self.label_10.setText(_translate("Dialog", "Smart clasification", None))
        self.groupBox_CustemR.setTitle(_translate("Dialog", "Custem regin", None))
        self.label_5.setText(_translate("Dialog", "colure ID", None))
        self.label.setText(_translate("Dialog", "width", None))
        self.label_2.setText(_translate("Dialog", "hight", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Name Identification", None))
        self.label_4.setText(_translate("Dialog", "name", None))
        self.label_3.setText(_translate("Dialog", "tag", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Identiication), _translate("Dialog", "Identiication", None))
        self.groupBox_x.setTitle(_translate("Dialog", "Channel x", None))
        self.groupBox_x_2.setTitle(_translate("Dialog", "Filtering", None))
        self.radioButton_noF_x.setText(_translate("Dialog", "no fitering", None))
        self.radioButton_lowPassF_x.setText(_translate("Dialog", "low pass filter", None))
        self.radioButton_gAve_x.setText(_translate("Dialog", "gaussian average", None))
        self.label_x.setText(_translate("Dialog", "frequency", None))
        self.label_x_2.setText(_translate("Dialog", "buffer size", None))
        self.groupBox_y.setTitle(_translate("Dialog", "Channel y", None))
        self.groupBox_y_2.setTitle(_translate("Dialog", "Filtering", None))
        self.radioButton_noF_y.setText(_translate("Dialog", "no fitering", None))
        self.radioButton_lowPassF_y.setText(_translate("Dialog", "low pass filter", None))
        self.radioButton_gAve_y.setText(_translate("Dialog", "gaussian average", None))
        self.label_y.setText(_translate("Dialog", "frequency", None))
        self.label_y_2.setText(_translate("Dialog", "buffer size", None))
        self.groupBox_w.setTitle(_translate("Dialog", "Channel w", None))
        self.groupBox_w_2.setTitle(_translate("Dialog", "Filtering", None))
        self.radioButton_noF_w.setText(_translate("Dialog", "no fitering", None))
        self.radioButton_lowPassF_w.setText(_translate("Dialog", "low pass filter", None))
        self.radioButton_gAve_w.setText(_translate("Dialog", "gaussian average", None))
        self.label_w.setText(_translate("Dialog", "frequency", None))
        self.label_w_2.setText(_translate("Dialog", "buffer size", None))
        self.groupBox_h.setTitle(_translate("Dialog", "Channel h", None))
        self.groupBox_h_2.setTitle(_translate("Dialog", "Filtering", None))
        self.radioButton_noF_h.setText(_translate("Dialog", "no fitering", None))
        self.radioButton_lowPassF_h.setText(_translate("Dialog", "low pass filter", None))
        self.radioButton_gAve_h.setText(_translate("Dialog", "gaussian average", None))
        self.label_h.setText(_translate("Dialog", "frequency", None))
        self.label_h_2.setText(_translate("Dialog", "buffer size", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.OutputChannels), _translate("Dialog", "OutputChannels", None))

