# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gregmeeresyoung\workspace\NagapifaceMocap\nagapi\designer\MocapMainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(404, 724)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 402, 642))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.graphicsView = MocapGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 411, 651))
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 400.0, 640.0))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 404, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Nagapi = QtGui.QMenu(self.menubar)
        self.menu_Nagapi.setObjectName(_fromUtf8("menu_Nagapi"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbout_nagapi_mocap = QtGui.QAction(MainWindow)
        self.actionAbout_nagapi_mocap.setObjectName(_fromUtf8("actionAbout_nagapi_mocap"))
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.actionResent_files = QtGui.QAction(MainWindow)
        self.actionResent_files.setObjectName(_fromUtf8("actionResent_files"))
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Save_as = QtGui.QAction(MainWindow)
        self.action_Save_as.setObjectName(_fromUtf8("action_Save_as"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.actionListenForConnections = QtGui.QAction(MainWindow)
        self.actionListenForConnections.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/ears2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionListenForConnections.setIcon(icon)
        self.actionListenForConnections.setObjectName(_fromUtf8("actionListenForConnections"))
        self.actionRawData = QtGui.QAction(MainWindow)
        self.actionRawData.setCheckable(True)
        self.actionRawData.setChecked(True)
        self.actionRawData.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/raw.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRawData.setIcon(icon1)
        self.actionRawData.setObjectName(_fromUtf8("actionRawData"))
        self.actionClassifiedData = QtGui.QAction(MainWindow)
        self.actionClassifiedData.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/identity6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClassifiedData.setIcon(icon2)
        self.actionClassifiedData.setObjectName(_fromUtf8("actionClassifiedData"))
        self.actionFilterData = QtGui.QAction(MainWindow)
        self.actionFilterData.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/drink161.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFilterData.setIcon(icon3)
        self.actionFilterData.setObjectName(_fromUtf8("actionFilterData"))
        self.actionAddClasificationRegen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/triangle7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddClasificationRegen.setIcon(icon4)
        self.actionAddClasificationRegen.setObjectName(_fromUtf8("actionAddClasificationRegen"))
        self.actionEditClasificationRegen = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/pencil90.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditClasificationRegen.setIcon(icon5)
        self.actionEditClasificationRegen.setObjectName(_fromUtf8("actionEditClasificationRegen"))
        self.actionRecordMocap = QtGui.QAction(MainWindow)
        self.actionRecordMocap.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/video35.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecordMocap.setIcon(icon6)
        self.actionRecordMocap.setObjectName(_fromUtf8("actionRecordMocap"))
        self.actionMocap_help = QtGui.QAction(MainWindow)
        self.actionMocap_help.setObjectName(_fromUtf8("actionMocap_help"))
        self.actionShow_markers = QtGui.QAction(MainWindow)
        self.actionShow_markers.setObjectName(_fromUtf8("actionShow_markers"))
        self.actionShow_marker_centers = QtGui.QAction(MainWindow)
        self.actionShow_marker_centers.setObjectName(_fromUtf8("actionShow_marker_centers"))
        self.actionShow_bg = QtGui.QAction(MainWindow)
        self.actionShow_bg.setObjectName(_fromUtf8("actionShow_bg"))
        self.actionDelet_selected = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/rubbish.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelet_selected.setIcon(icon7)
        self.actionDelet_selected.setObjectName(_fromUtf8("actionDelet_selected"))
        self.actionPrefrenses = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools/music236.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrefrenses.setIcon(icon8)
        self.actionPrefrenses.setObjectName(_fromUtf8("actionPrefrenses"))
        self.menu_Nagapi.addAction(self.actionAbout_nagapi_mocap)
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.actionResent_files)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Save_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Close)
        self.menu_Edit.addAction(self.actionDelet_selected)
        self.menu_Edit.addAction(self.actionAddClasificationRegen)
        self.menu_Edit.addAction(self.actionEditClasificationRegen)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionPrefrenses)
        self.menu_View.addAction(self.actionShow_markers)
        self.menu_View.addAction(self.actionShow_marker_centers)
        self.menu_View.addAction(self.actionShow_bg)
        self.menu_Help.addAction(self.actionMocap_help)
        self.menubar.addAction(self.menu_Nagapi.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionListenForConnections)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRawData)
        self.toolBar.addAction(self.actionClassifiedData)
        self.toolBar.addAction(self.actionFilterData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAddClasificationRegen)
        self.toolBar.addAction(self.actionEditClasificationRegen)
        self.toolBar.addAction(self.actionDelet_selected)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRecordMocap)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Nagapi Mocap", None))
        self.menu_Nagapi.setTitle(_translate("MainWindow", "&Nagapi", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAbout_nagapi_mocap.setText(_translate("MainWindow", "about nagapi mocap", None))
        self.action_New.setText(_translate("MainWindow", "&New", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.actionResent_files.setText(_translate("MainWindow", "resent files", None))
        self.action_Save.setText(_translate("MainWindow", "&Save", None))
        self.action_Save_as.setText(_translate("MainWindow", "&Save as", None))
        self.action_Close.setText(_translate("MainWindow", "&Close", None))
        self.actionListenForConnections.setText(_translate("MainWindow", "ListenForConnections", None))
        self.actionListenForConnections.setToolTip(_translate("MainWindow", "listen for incomming connections", None))
        self.actionRawData.setText(_translate("MainWindow", "RawData", None))
        self.actionRawData.setToolTip(_translate("MainWindow", "raw data", None))
        self.actionClassifiedData.setText(_translate("MainWindow", "ClassifiedData", None))
        self.actionClassifiedData.setToolTip(_translate("MainWindow", "Classified data", None))
        self.actionFilterData.setText(_translate("MainWindow", "FilterData", None))
        self.actionFilterData.setToolTip(_translate("MainWindow", "filter data", None))
        self.actionAddClasificationRegen.setText(_translate("MainWindow", "AddClasificationRegen", None))
        self.actionAddClasificationRegen.setToolTip(_translate("MainWindow", "add clasification regen", None))
        self.actionEditClasificationRegen.setText(_translate("MainWindow", "EditClasificationRegen", None))
        self.actionEditClasificationRegen.setToolTip(_translate("MainWindow", "edit clasification regen", None))
        self.actionRecordMocap.setText(_translate("MainWindow", "RecordMocap", None))
        self.actionRecordMocap.setToolTip(_translate("MainWindow", "recod mocap", None))
        self.actionMocap_help.setText(_translate("MainWindow", "mocap help", None))
        self.actionShow_markers.setText(_translate("MainWindow", "show markers", None))
        self.actionShow_marker_centers.setText(_translate("MainWindow", "show marker centers", None))
        self.actionShow_bg.setText(_translate("MainWindow", "show bg", None))
        self.actionDelet_selected.setText(_translate("MainWindow", "delete selected", None))
        self.actionDelet_selected.setShortcut(_translate("MainWindow", "Backspace", None))
        self.actionPrefrenses.setText(_translate("MainWindow", "prefrenses", None))

from MocapGraphicsView import MocapGraphicsView
import nagapiMocapIcons_rc
